#!/usr/bin/env node

var fs = require('fs');
var yaml = require('js-yaml');
var argv = process.argv;

if (!argv[2] || !argv[3] || !fs.existsSync(argv[2])) {
    console.warn('Usage: json2yaml [from.json] [to.yml]');
    process.exit(1);
}

var json = JSON.parse(fs.readFileSync(argv[2], 'utf8'));
fs.writeFileSync(argv[3], yaml.dump(json));
